# Generated by Django 3.0.2 on 2020-01-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='updateDate',
            field=models.DateTimeField(null=True),
        ),
    ]
