# Generated by Django 2.2.9 on 2020-06-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
